{"general": ["list index out of range", "urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5462808910:AAGDKsBtsM4B5Lc93rdfS3wX_YjvBnl-tYg/sendMessage (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f3f5d0d2510>: Failed to establish a new connection: [Errno 101] Network is unreachable'))", 1321.07, 1321.07, false, false, false, false, false, false, false, false]}